/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PetsRouteImport } from './routes/pets'
import { Route as OwnersRouteImport } from './routes/owners'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsultantRouteImport } from './routes/consultant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VademecumIndexRouteImport } from './routes/vademecum.index'
import { Route as VaccinationsIndexRouteImport } from './routes/vaccinations.index'
import { Route as SurgeriesIndexRouteImport } from './routes/surgeries.index'
import { Route as ProceduresIndexRouteImport } from './routes/procedures.index'
import { Route as PetsIndexRouteImport } from './routes/pets.index'
import { Route as OwnersIndexRouteImport } from './routes/owners.index'
import { Route as OrganizationIndexRouteImport } from './routes/organization.index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as AppointmentsIndexRouteImport } from './routes/appointments.index'
import { Route as VaccinationsNewRouteImport } from './routes/vaccinations.new'
import { Route as SurgeriesSurgeryIdRouteImport } from './routes/surgeries.$surgeryId'
import { Route as PetsNewRouteImport } from './routes/pets.new'
import { Route as PetsPetIdRouteImport } from './routes/pets.$petId'
import { Route as OwnersNewRouteImport } from './routes/owners.new'
import { Route as OwnersOwnerIdRouteImport } from './routes/owners.$ownerId'
import { Route as OrganizationOrganizationIdRouteImport } from './routes/organization.$organizationId'
import { Route as ConsultationsNewRouteImport } from './routes/consultations.new'
import { Route as AppointmentsAppointmentIdRouteImport } from './routes/appointments.$appointmentId'
import { Route as PetsNewIndexRouteImport } from './routes/pets.new.index'
import { Route as OwnersNewIndexRouteImport } from './routes/owners.new.index'
import { Route as PetsNewVerifyRouteImport } from './routes/pets.new.verify'
import { Route as PetsPetIdHistoryRouteImport } from './routes/pets.$petId.history'
import { Route as OwnersNewVerifyRouteImport } from './routes/owners.new.verify'
import { Route as OrganizationOrganizationIdEditRouteImport } from './routes/organization.$organizationId.edit'

const PetsRoute = PetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersRoute = OwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantRoute = ConsultantRouteImport.update({
  id: '/consultant',
  path: '/consultant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VademecumIndexRoute = VademecumIndexRouteImport.update({
  id: '/vademecum/',
  path: '/vademecum/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaccinationsIndexRoute = VaccinationsIndexRouteImport.update({
  id: '/vaccinations/',
  path: '/vaccinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurgeriesIndexRoute = SurgeriesIndexRouteImport.update({
  id: '/surgeries/',
  path: '/surgeries/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresIndexRoute = ProceduresIndexRouteImport.update({
  id: '/procedures/',
  path: '/procedures/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsIndexRoute = PetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PetsRoute,
} as any)
const OwnersIndexRoute = OwnersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnersRoute,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaccinationsNewRoute = VaccinationsNewRouteImport.update({
  id: '/vaccinations/new',
  path: '/vaccinations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SurgeriesSurgeryIdRoute = SurgeriesSurgeryIdRouteImport.update({
  id: '/surgeries/$surgeryId',
  path: '/surgeries/$surgeryId',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsNewRoute = PetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PetsRoute,
} as any)
const PetsPetIdRoute = PetsPetIdRouteImport.update({
  id: '/$petId',
  path: '/$petId',
  getParentRoute: () => PetsRoute,
} as any)
const OwnersNewRoute = OwnersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OwnersRoute,
} as any)
const OwnersOwnerIdRoute = OwnersOwnerIdRouteImport.update({
  id: '/$ownerId',
  path: '/$ownerId',
  getParentRoute: () => OwnersRoute,
} as any)
const OrganizationOrganizationIdRoute =
  OrganizationOrganizationIdRouteImport.update({
    id: '/organization/$organizationId',
    path: '/organization/$organizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsultationsNewRoute = ConsultationsNewRouteImport.update({
  id: '/consultations/new',
  path: '/consultations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsAppointmentIdRoute =
  AppointmentsAppointmentIdRouteImport.update({
    id: '/appointments/$appointmentId',
    path: '/appointments/$appointmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PetsNewIndexRoute = PetsNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PetsNewRoute,
} as any)
const OwnersNewIndexRoute = OwnersNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnersNewRoute,
} as any)
const PetsNewVerifyRoute = PetsNewVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => PetsNewRoute,
} as any)
const PetsPetIdHistoryRoute = PetsPetIdHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PetsPetIdRoute,
} as any)
const OwnersNewVerifyRoute = OwnersNewVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => OwnersNewRoute,
} as any)
const OrganizationOrganizationIdEditRoute =
  OrganizationOrganizationIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => OrganizationOrganizationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consultant': typeof ConsultantRoute
  '/login': typeof LoginRoute
  '/owners': typeof OwnersRouteWithChildren
  '/pets': typeof PetsRouteWithChildren
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
  '/consultations/new': typeof ConsultationsNewRoute
  '/organization/$organizationId': typeof OrganizationOrganizationIdRouteWithChildren
  '/owners/$ownerId': typeof OwnersOwnerIdRoute
  '/owners/new': typeof OwnersNewRouteWithChildren
  '/pets/$petId': typeof PetsPetIdRouteWithChildren
  '/pets/new': typeof PetsNewRouteWithChildren
  '/surgeries/$surgeryId': typeof SurgeriesSurgeryIdRoute
  '/vaccinations/new': typeof VaccinationsNewRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/organization': typeof OrganizationIndexRoute
  '/owners/': typeof OwnersIndexRoute
  '/pets/': typeof PetsIndexRoute
  '/procedures': typeof ProceduresIndexRoute
  '/surgeries': typeof SurgeriesIndexRoute
  '/vaccinations': typeof VaccinationsIndexRoute
  '/vademecum': typeof VademecumIndexRoute
  '/organization/$organizationId/edit': typeof OrganizationOrganizationIdEditRoute
  '/owners/new/verify': typeof OwnersNewVerifyRoute
  '/pets/$petId/history': typeof PetsPetIdHistoryRoute
  '/pets/new/verify': typeof PetsNewVerifyRoute
  '/owners/new/': typeof OwnersNewIndexRoute
  '/pets/new/': typeof PetsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consultant': typeof ConsultantRoute
  '/login': typeof LoginRoute
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
  '/consultations/new': typeof ConsultationsNewRoute
  '/organization/$organizationId': typeof OrganizationOrganizationIdRouteWithChildren
  '/owners/$ownerId': typeof OwnersOwnerIdRoute
  '/pets/$petId': typeof PetsPetIdRouteWithChildren
  '/surgeries/$surgeryId': typeof SurgeriesSurgeryIdRoute
  '/vaccinations/new': typeof VaccinationsNewRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/organization': typeof OrganizationIndexRoute
  '/owners': typeof OwnersIndexRoute
  '/pets': typeof PetsIndexRoute
  '/procedures': typeof ProceduresIndexRoute
  '/surgeries': typeof SurgeriesIndexRoute
  '/vaccinations': typeof VaccinationsIndexRoute
  '/vademecum': typeof VademecumIndexRoute
  '/organization/$organizationId/edit': typeof OrganizationOrganizationIdEditRoute
  '/owners/new/verify': typeof OwnersNewVerifyRoute
  '/pets/$petId/history': typeof PetsPetIdHistoryRoute
  '/pets/new/verify': typeof PetsNewVerifyRoute
  '/owners/new': typeof OwnersNewIndexRoute
  '/pets/new': typeof PetsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consultant': typeof ConsultantRoute
  '/login': typeof LoginRoute
  '/owners': typeof OwnersRouteWithChildren
  '/pets': typeof PetsRouteWithChildren
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
  '/consultations/new': typeof ConsultationsNewRoute
  '/organization/$organizationId': typeof OrganizationOrganizationIdRouteWithChildren
  '/owners/$ownerId': typeof OwnersOwnerIdRoute
  '/owners/new': typeof OwnersNewRouteWithChildren
  '/pets/$petId': typeof PetsPetIdRouteWithChildren
  '/pets/new': typeof PetsNewRouteWithChildren
  '/surgeries/$surgeryId': typeof SurgeriesSurgeryIdRoute
  '/vaccinations/new': typeof VaccinationsNewRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/owners/': typeof OwnersIndexRoute
  '/pets/': typeof PetsIndexRoute
  '/procedures/': typeof ProceduresIndexRoute
  '/surgeries/': typeof SurgeriesIndexRoute
  '/vaccinations/': typeof VaccinationsIndexRoute
  '/vademecum/': typeof VademecumIndexRoute
  '/organization/$organizationId/edit': typeof OrganizationOrganizationIdEditRoute
  '/owners/new/verify': typeof OwnersNewVerifyRoute
  '/pets/$petId/history': typeof PetsPetIdHistoryRoute
  '/pets/new/verify': typeof PetsNewVerifyRoute
  '/owners/new/': typeof OwnersNewIndexRoute
  '/pets/new/': typeof PetsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consultant'
    | '/login'
    | '/owners'
    | '/pets'
    | '/appointments/$appointmentId'
    | '/consultations/new'
    | '/organization/$organizationId'
    | '/owners/$ownerId'
    | '/owners/new'
    | '/pets/$petId'
    | '/pets/new'
    | '/surgeries/$surgeryId'
    | '/vaccinations/new'
    | '/appointments'
    | '/inventory'
    | '/organization'
    | '/owners/'
    | '/pets/'
    | '/procedures'
    | '/surgeries'
    | '/vaccinations'
    | '/vademecum'
    | '/organization/$organizationId/edit'
    | '/owners/new/verify'
    | '/pets/$petId/history'
    | '/pets/new/verify'
    | '/owners/new/'
    | '/pets/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consultant'
    | '/login'
    | '/appointments/$appointmentId'
    | '/consultations/new'
    | '/organization/$organizationId'
    | '/owners/$ownerId'
    | '/pets/$petId'
    | '/surgeries/$surgeryId'
    | '/vaccinations/new'
    | '/appointments'
    | '/inventory'
    | '/organization'
    | '/owners'
    | '/pets'
    | '/procedures'
    | '/surgeries'
    | '/vaccinations'
    | '/vademecum'
    | '/organization/$organizationId/edit'
    | '/owners/new/verify'
    | '/pets/$petId/history'
    | '/pets/new/verify'
    | '/owners/new'
    | '/pets/new'
  id:
    | '__root__'
    | '/'
    | '/consultant'
    | '/login'
    | '/owners'
    | '/pets'
    | '/appointments/$appointmentId'
    | '/consultations/new'
    | '/organization/$organizationId'
    | '/owners/$ownerId'
    | '/owners/new'
    | '/pets/$petId'
    | '/pets/new'
    | '/surgeries/$surgeryId'
    | '/vaccinations/new'
    | '/appointments/'
    | '/inventory/'
    | '/organization/'
    | '/owners/'
    | '/pets/'
    | '/procedures/'
    | '/surgeries/'
    | '/vaccinations/'
    | '/vademecum/'
    | '/organization/$organizationId/edit'
    | '/owners/new/verify'
    | '/pets/$petId/history'
    | '/pets/new/verify'
    | '/owners/new/'
    | '/pets/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultantRoute: typeof ConsultantRoute
  LoginRoute: typeof LoginRoute
  OwnersRoute: typeof OwnersRouteWithChildren
  PetsRoute: typeof PetsRouteWithChildren
  AppointmentsAppointmentIdRoute: typeof AppointmentsAppointmentIdRoute
  ConsultationsNewRoute: typeof ConsultationsNewRoute
  OrganizationOrganizationIdRoute: typeof OrganizationOrganizationIdRouteWithChildren
  SurgeriesSurgeryIdRoute: typeof SurgeriesSurgeryIdRoute
  VaccinationsNewRoute: typeof VaccinationsNewRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
  ProceduresIndexRoute: typeof ProceduresIndexRoute
  SurgeriesIndexRoute: typeof SurgeriesIndexRoute
  VaccinationsIndexRoute: typeof VaccinationsIndexRoute
  VademecumIndexRoute: typeof VademecumIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pets': {
      id: '/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners': {
      id: '/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof OwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant': {
      id: '/consultant'
      path: '/consultant'
      fullPath: '/consultant'
      preLoaderRoute: typeof ConsultantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vademecum/': {
      id: '/vademecum/'
      path: '/vademecum'
      fullPath: '/vademecum'
      preLoaderRoute: typeof VademecumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaccinations/': {
      id: '/vaccinations/'
      path: '/vaccinations'
      fullPath: '/vaccinations'
      preLoaderRoute: typeof VaccinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surgeries/': {
      id: '/surgeries/'
      path: '/surgeries'
      fullPath: '/surgeries'
      preLoaderRoute: typeof SurgeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures/': {
      id: '/procedures/'
      path: '/procedures'
      fullPath: '/procedures'
      preLoaderRoute: typeof ProceduresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/': {
      id: '/pets/'
      path: '/'
      fullPath: '/pets/'
      preLoaderRoute: typeof PetsIndexRouteImport
      parentRoute: typeof PetsRoute
    }
    '/owners/': {
      id: '/owners/'
      path: '/'
      fullPath: '/owners/'
      preLoaderRoute: typeof OwnersIndexRouteImport
      parentRoute: typeof OwnersRoute
    }
    '/organization/': {
      id: '/organization/'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaccinations/new': {
      id: '/vaccinations/new'
      path: '/vaccinations/new'
      fullPath: '/vaccinations/new'
      preLoaderRoute: typeof VaccinationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surgeries/$surgeryId': {
      id: '/surgeries/$surgeryId'
      path: '/surgeries/$surgeryId'
      fullPath: '/surgeries/$surgeryId'
      preLoaderRoute: typeof SurgeriesSurgeryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/new': {
      id: '/pets/new'
      path: '/new'
      fullPath: '/pets/new'
      preLoaderRoute: typeof PetsNewRouteImport
      parentRoute: typeof PetsRoute
    }
    '/pets/$petId': {
      id: '/pets/$petId'
      path: '/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof PetsPetIdRouteImport
      parentRoute: typeof PetsRoute
    }
    '/owners/new': {
      id: '/owners/new'
      path: '/new'
      fullPath: '/owners/new'
      preLoaderRoute: typeof OwnersNewRouteImport
      parentRoute: typeof OwnersRoute
    }
    '/owners/$ownerId': {
      id: '/owners/$ownerId'
      path: '/$ownerId'
      fullPath: '/owners/$ownerId'
      preLoaderRoute: typeof OwnersOwnerIdRouteImport
      parentRoute: typeof OwnersRoute
    }
    '/organization/$organizationId': {
      id: '/organization/$organizationId'
      path: '/organization/$organizationId'
      fullPath: '/organization/$organizationId'
      preLoaderRoute: typeof OrganizationOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations/new': {
      id: '/consultations/new'
      path: '/consultations/new'
      fullPath: '/consultations/new'
      preLoaderRoute: typeof ConsultationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/$appointmentId': {
      id: '/appointments/$appointmentId'
      path: '/appointments/$appointmentId'
      fullPath: '/appointments/$appointmentId'
      preLoaderRoute: typeof AppointmentsAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/new/': {
      id: '/pets/new/'
      path: '/'
      fullPath: '/pets/new/'
      preLoaderRoute: typeof PetsNewIndexRouteImport
      parentRoute: typeof PetsNewRoute
    }
    '/owners/new/': {
      id: '/owners/new/'
      path: '/'
      fullPath: '/owners/new/'
      preLoaderRoute: typeof OwnersNewIndexRouteImport
      parentRoute: typeof OwnersNewRoute
    }
    '/pets/new/verify': {
      id: '/pets/new/verify'
      path: '/verify'
      fullPath: '/pets/new/verify'
      preLoaderRoute: typeof PetsNewVerifyRouteImport
      parentRoute: typeof PetsNewRoute
    }
    '/pets/$petId/history': {
      id: '/pets/$petId/history'
      path: '/history'
      fullPath: '/pets/$petId/history'
      preLoaderRoute: typeof PetsPetIdHistoryRouteImport
      parentRoute: typeof PetsPetIdRoute
    }
    '/owners/new/verify': {
      id: '/owners/new/verify'
      path: '/verify'
      fullPath: '/owners/new/verify'
      preLoaderRoute: typeof OwnersNewVerifyRouteImport
      parentRoute: typeof OwnersNewRoute
    }
    '/organization/$organizationId/edit': {
      id: '/organization/$organizationId/edit'
      path: '/edit'
      fullPath: '/organization/$organizationId/edit'
      preLoaderRoute: typeof OrganizationOrganizationIdEditRouteImport
      parentRoute: typeof OrganizationOrganizationIdRoute
    }
  }
}

interface OwnersNewRouteChildren {
  OwnersNewVerifyRoute: typeof OwnersNewVerifyRoute
  OwnersNewIndexRoute: typeof OwnersNewIndexRoute
}

const OwnersNewRouteChildren: OwnersNewRouteChildren = {
  OwnersNewVerifyRoute: OwnersNewVerifyRoute,
  OwnersNewIndexRoute: OwnersNewIndexRoute,
}

const OwnersNewRouteWithChildren = OwnersNewRoute._addFileChildren(
  OwnersNewRouteChildren,
)

interface OwnersRouteChildren {
  OwnersOwnerIdRoute: typeof OwnersOwnerIdRoute
  OwnersNewRoute: typeof OwnersNewRouteWithChildren
  OwnersIndexRoute: typeof OwnersIndexRoute
}

const OwnersRouteChildren: OwnersRouteChildren = {
  OwnersOwnerIdRoute: OwnersOwnerIdRoute,
  OwnersNewRoute: OwnersNewRouteWithChildren,
  OwnersIndexRoute: OwnersIndexRoute,
}

const OwnersRouteWithChildren =
  OwnersRoute._addFileChildren(OwnersRouteChildren)

interface PetsPetIdRouteChildren {
  PetsPetIdHistoryRoute: typeof PetsPetIdHistoryRoute
}

const PetsPetIdRouteChildren: PetsPetIdRouteChildren = {
  PetsPetIdHistoryRoute: PetsPetIdHistoryRoute,
}

const PetsPetIdRouteWithChildren = PetsPetIdRoute._addFileChildren(
  PetsPetIdRouteChildren,
)

interface PetsNewRouteChildren {
  PetsNewVerifyRoute: typeof PetsNewVerifyRoute
  PetsNewIndexRoute: typeof PetsNewIndexRoute
}

const PetsNewRouteChildren: PetsNewRouteChildren = {
  PetsNewVerifyRoute: PetsNewVerifyRoute,
  PetsNewIndexRoute: PetsNewIndexRoute,
}

const PetsNewRouteWithChildren =
  PetsNewRoute._addFileChildren(PetsNewRouteChildren)

interface PetsRouteChildren {
  PetsPetIdRoute: typeof PetsPetIdRouteWithChildren
  PetsNewRoute: typeof PetsNewRouteWithChildren
  PetsIndexRoute: typeof PetsIndexRoute
}

const PetsRouteChildren: PetsRouteChildren = {
  PetsPetIdRoute: PetsPetIdRouteWithChildren,
  PetsNewRoute: PetsNewRouteWithChildren,
  PetsIndexRoute: PetsIndexRoute,
}

const PetsRouteWithChildren = PetsRoute._addFileChildren(PetsRouteChildren)

interface OrganizationOrganizationIdRouteChildren {
  OrganizationOrganizationIdEditRoute: typeof OrganizationOrganizationIdEditRoute
}

const OrganizationOrganizationIdRouteChildren: OrganizationOrganizationIdRouteChildren =
  {
    OrganizationOrganizationIdEditRoute: OrganizationOrganizationIdEditRoute,
  }

const OrganizationOrganizationIdRouteWithChildren =
  OrganizationOrganizationIdRoute._addFileChildren(
    OrganizationOrganizationIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultantRoute: ConsultantRoute,
  LoginRoute: LoginRoute,
  OwnersRoute: OwnersRouteWithChildren,
  PetsRoute: PetsRouteWithChildren,
  AppointmentsAppointmentIdRoute: AppointmentsAppointmentIdRoute,
  ConsultationsNewRoute: ConsultationsNewRoute,
  OrganizationOrganizationIdRoute: OrganizationOrganizationIdRouteWithChildren,
  SurgeriesSurgeryIdRoute: SurgeriesSurgeryIdRoute,
  VaccinationsNewRoute: VaccinationsNewRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
  ProceduresIndexRoute: ProceduresIndexRoute,
  SurgeriesIndexRoute: SurgeriesIndexRoute,
  VaccinationsIndexRoute: VaccinationsIndexRoute,
  VademecumIndexRoute: VademecumIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
